region = "ap-southeast-2"
resource_prefix = "HYERIM-TERRAFORM-PROVISIONING"
#vpc_cidr = "10.0.0.0/16"
subnet_id = "subnet-008a92fe71c69f8fd"
instance_type = "t2.micro.miro"
key_pair_name = "devos-demo-sydney-target-instance-key"
